function [uX, uY] = control_input(K1, K2, W, Theta, h, h_dot, i, num_agents)
    local_sum = zeros(1,4);  % size: 4x1
    for j = 1: num_agents
        local_sum = local_sum + ...
                    (W(i,j) * ( (Theta(j,:) - h(j,:)) ...
                                - (Theta(i,:)-h(i,:)) ...
                                )...
                    )' ; %% size 4x1
    end
    
    % size: 1st term: K1*Theta(i,X)         size: (1x2)*(2x1) = 1x1
    % size: 2nd term: K2*Summation(j-i,X)   size: (1x2)*(2x1) = 1x1
    % size: 3rd term: h_dot(i,Y)            size: (1x1)
    uX =    K1*(Theta(i,1:2)' - h(i,1:2)') ...
            + K2*local_sum(1:2,1) ...
            + h_dot(i,2) ;

    % size: 1st term: K1*Theta(i,Y)         size: (1x2)*(2x1) = 1x1
    % size: 2nd term: K2*Summation(j-i,Y)   size: (1x2)*(2x1) = 1x1
    % size: 3rd term: h_dot(i,Y)            size: (1x1)
    uY =    K1*(Theta(i,3:4)' - h(i,3:4)') ...
            + K2*local_sum(3:4 ,1) ...
            + h_dot(i,4) ;