function h_dot = formation_func_dot(t, w, r, num_agents, h_dot)
    % Size: num_agents x 4 (i.e. 5 x 4)
    for i = 1:num_agents
        h_dot(i,:)=[- w * r * sin(w*t + 2*pi*(i - 1)/5) * g(t,i,w), ...
                    - w^2 * r * cos(w*t + 2*pi*(i - 1)/5) * g(t,i,w),...
                    w * r * cos(w*t + 2*pi*(i - 1)/5),...
                    - w^2 * r * sin(w*t + 2*pi*(i - 1)/5)   ] ;
    end