function h = formation_func(t, w, r, num_agents, h)
    % Size: num_agents x 4 (i.e. 5 x 4)
    for i = 1:num_agents
        h(i,:)=[r * cos((w*t) + 2*pi*(i-1)/5 - 1) * g(t,i,w), ...
                - w * r * sin(w*t + 2*pi*(i - 1)/5) * g(t,i,w),...
                r * sin(w*t + 2*pi*(i - 1)/5),...
                w * r * cos(w*t + 2*pi*(i - 1)/5)   ]' ;
    end